# =============================================================================
# validate.jl — the numerical validation study for the FP32 rendering pipeline.
# =============================================================================
#
# Produces lab/validation_report.md: hard numbers behind the project's central
# precision claim — that baking ψ's separable factors into Float32 tables in
# extended precision, then reconstructing ψ on the GPU in pure FP32, is
# visually indistinguishable from exact evaluation.
#
# Sections:
#   1. Float64 recurrences vs BigFloat        (how good is the fast reference?)
#   2. Float32 *direct* recurrences vs BigFloat  (the baseline replaced by
#      the table approach)
#   3. Table-size sweep on the worst states   (why 8192/4096 samples)
#   4. Full production-size table sweep       (worst per-factor error, all states)
#   5. End-to-end FP32 ψ reconstruction       (the headline number)
#   6. Display-stats grid convergence         (are the baked quantiles stable?)
#
# Error metric throughout: max |approx − truth| / scale, where `scale` is the
# factor's (or state's) global peak magnitude. Pointwise relative error is
# meaningless at nodes, and errors relative to the brightest features are what
# the eye can actually see. Probe points are interval midpoints — the worst
# case for linear interpolation.
#
# Run:  julia --project=lab -t auto lab/scripts/validate.jl     (~2–4 minutes)
# =============================================================================

using HydrogenLab
using Printf
using Random

const NMAX = 10
const RADIAL_SAMPLES = 8192
const ANGULAR_SAMPLES = 4096

fmt(x) = @sprintf("%.2e", x)

# Scaled-error helper (see header): everything is Float64 by the time it is
# compared; `truth` arrives as BigFloat and is narrowed after the subtraction.
serr(approx, truth, scale) = Float64(abs(approx - truth)) / scale

report = IOBuffer()
println(report, "# HydrogenLab validation report")
println(report)
println(report, "Generated by `lab/scripts/validate.jl` — n ≤ $NMAX, ",
        "radial/angular table sizes $RADIAL_SAMPLES/$ANGULAR_SAMPLES, ",
        "$(Threads.nthreads()) threads.")
println(report)
println(report, "Error metric: max |approx − truth| / (global peak of the ",
        "factor or state), probed at interpolation-worst-case midpoints; ",
        "truth is BigFloat (256-bit).")

# -----------------------------------------------------------------------------
# 1 & 2. Recurrence accuracy: Float64 and Float32 direct evaluation.
#
# Dense probe grids (denser than any table) over each factor's full domain.
# -----------------------------------------------------------------------------
println(report, "\n## 1–2. Direct recurrence evaluation vs BigFloat\n")

rad_states = [(n, l) for n in 1:NMAX for l in 0:(n - 1)]
ang_states = [(l, m) for l in 0:(NMAX - 1) for m in 0:l]

# Worker: worst scaled error of direct evaluation in precision T over a probe grid.
function direct_radial_err(::Type{T}, n, l; probes = 4000) where {T}
    rmax = safe_clip_radius(n, l)
    Nb = radial_norm(BigFloat, n, l)
    NT = radial_norm(T, n, l)
    scale = Float64(maximum(abs(radial(n, l, BigFloat(radial_node(i, 513, rmax)), Nb))
                            for i in 1:513))          # coarse but adequate peak
    worst = 0.0
    for i in 1:probes
        r = rmax * ((i - 0.5) / probes)^2             # same √ clustering as tables
        worst = max(worst, serr(radial(n, l, T(r), NT),
                                radial(n, l, BigFloat(r), Nb), scale))
    end
    return worst
end

function direct_angular_err(::Type{T}, l, m; probes = 4000) where {T}
    scale = Float64(maximum(abs(plm_norm(l, m, cospi(BigFloat(j) / 256)))
                            for j in 0:256))
    worst = 0.0
    for i in 1:probes
        θ = π * (i - 0.5) / probes
        # cos(T(θ)): the direct path receives θ (well-conditioned), mirroring
        # how a direct-evaluation shader would compute u = cos(atan2(...)).
        worst = max(worst, serr(plm_norm(l, m, cos(T(θ))),
                                plm_norm(l, m, cos(BigFloat(θ))), scale))
    end
    return worst
end

for (T, label) in ((Float64, "Float64 (lab reference path)"),
                   (Float32, "Float32 (what direct in-shader recurrences would do)"))
    rerrs = zeros(length(rad_states))
    Threads.@threads for i in eachindex(rad_states)
        rerrs[i] = direct_radial_err(T, rad_states[i]...)
    end
    aerrs = zeros(length(ang_states))
    Threads.@threads for i in eachindex(ang_states)
        aerrs[i] = direct_angular_err(T, ang_states[i]...)
    end
    ri, ai = argmax(rerrs), argmax(aerrs)
    println(report, "- **$label** — worst radial: ", fmt(rerrs[ri]),
            " at (n,l)=", rad_states[ri], "; worst angular: ", fmt(aerrs[ai]),
            " at (l,m)=", ang_states[ai])
end

# -----------------------------------------------------------------------------
# 3. Table-size sweep on the hardest states.
#
# Radial hardness ∝ oscillation count × extent → (n,l) = (10,0).
# Angular hardness ∝ l → probe l = 9 at m = 0 (full oscillation span).
# -----------------------------------------------------------------------------
println(report, "\n## 3. Table-size sweep (hardest states)\n")
println(report, "| samples | radial (10,0) | angular (9,0) |")
println(report, "|---------|---------------|---------------|")

function table_radial_err(n, l, samples)
    tab = bake_radial(n, l, samples)
    scale = Float64(maximum(abs, tab.values))
    Nb = radial_norm(BigFloat, n, l)
    worst = 0.0
    for i in 1:(samples - 1)
        r = (radial_node(i, samples, tab.r_max) + radial_node(i + 1, samples, tab.r_max)) / 2
        worst = max(worst, serr(lookup_radial(tab, Float32(r)),
                                radial(n, l, BigFloat(r), Nb), scale))
    end
    return worst
end

function table_angular_err(l, m, samples)
    tab = bake_angular(l, m, samples)
    scale = Float64(maximum(abs, tab.values))
    worst = 0.0
    for i in 1:(samples - 1)
        θ = π * (i - 0.5) / (samples - 1)
        worst = max(worst, serr(lookup_angular(tab, Float32(θ)),
                                plm_norm(l, m, cos(BigFloat(θ))), scale))
    end
    return worst
end

for samples in (1024, 2048, 4096, 8192, 16384)
    @printf(IOContext(report), "| %5d | %s | %s |\n", samples,
            fmt(table_radial_err(10, 0, samples)),
            fmt(table_angular_err(9, 0, samples)))
end

# -----------------------------------------------------------------------------
# 4. Production-size sweep over every table.
# -----------------------------------------------------------------------------
println(report, "\n## 4. Production tables, all states\n")

rt_errs = zeros(length(rad_states))
Threads.@threads for i in eachindex(rad_states)
    rt_errs[i] = table_radial_err(rad_states[i]..., RADIAL_SAMPLES)
end
at_errs = zeros(length(ang_states))
Threads.@threads for i in eachindex(ang_states)
    at_errs[i] = table_angular_err(ang_states[i]..., ANGULAR_SAMPLES)
end
ri, ai = argmax(rt_errs), argmax(at_errs)
println(report, "- Worst radial-table error: **", fmt(rt_errs[ri]), "** at (n,l)=",
        rad_states[ri], " (", RADIAL_SAMPLES, " samples)")
println(report, "- Worst angular-table error: **", fmt(at_errs[ai]), "** at (l,m)=",
        ang_states[ai], " (", ANGULAR_SAMPLES, " samples)")

# -----------------------------------------------------------------------------
# 5. End-to-end FP32 ψ reconstruction — the headline.
#
# For every state and both modes: random points in the framing ball, ψ rebuilt
# exactly as the shader will (Float32 tables, Float32 lerp, Float32 sincos,
# Float32 √2 factors), against BigFloat ψ, scaled by the state's peak |ψ|
# (√max_density from the display stats).
# -----------------------------------------------------------------------------
println(report, "\n## 5. End-to-end FP32 ψ reconstruction\n")

"ψ as the GPU reconstructs it, entirely in Float32. Note the coordinate path:
θ from two-argument atan (never u = z/r; see `lookup_angular` for why)."
function psi_fp32(rt::RadialTable, at::AngularTable, m::Int, real_mode::Bool,
                  x::Float32, y::Float32, z::Float32)
    ρc = sqrt(x * x + y * y)              # cylindrical radius
    r = sqrt(ρc * ρc + z * z)
    θ = atan(ρc, z)                       # polar angle ∈ [0, π], well-conditioned
    φ = atan(y, x)
    R = lookup_radial(rt, r)
    P = lookup_angular(at, θ)
    am = abs(m)
    flip = isodd(am) ? -1.0f0 : 1.0f0
    if real_mode
        azim = m == 0 ? 1.0f0 :
               m > 0 ? sqrt(2.0f0) * flip * cos(am * φ) :
                       sqrt(2.0f0) * flip * sin(am * φ)
        return ComplexF32(R * P * azim, 0.0f0)
    else
        sgn = m < 0 ? flip : 1.0f0
        sφ, cφ = sincos(m * φ)
        return ComplexF32(sgn * R * P * cφ, sgn * R * P * sφ)
    end
end

all_states = [(n, l, m) for n in 1:NMAX for l in 0:(n - 1) for m in (-l):l]
worst_by_state = zeros(length(all_states))
Threads.@threads for si in eachindex(all_states)
    n, l, m = all_states[si]
    rt = bake_radial(n, l, RADIAL_SAMPLES)
    at = bake_angular(l, abs(m), ANGULAR_SAMPLES)
    rng = Xoshiro(1000 + si)                        # reproducible per state
    rframe = r_max_for(n)
    worst = 0.0
    for mode in (true, false)
        scale = sqrt(display_stats(n, l, m, mode).max_density)
        for _ in 1:2000
            # Uniform in the framing ball via rejection from the cube.
            x, y, z = (2rand(rng) - 1, 2rand(rng) - 1, 2rand(rng) - 1) .* rframe
            x^2 + y^2 + z^2 > rframe^2 && continue
            approx = psi_fp32(rt, at, m, mode, Float32(x), Float32(y), Float32(z))
            truth = psi_cartesian(n, l, m, BigFloat(x), BigFloat(y), BigFloat(z);
                                  real_mode = mode)
            worst = max(worst, Float64(abs(approx - ComplexF64(truth))) / scale)
        end
    end
    worst_by_state[si] = worst
end
wi = argmax(worst_by_state)
println(report, "- States × modes probed: ", length(all_states), " × 2, ",
        "~2000 random points each")
println(report, "- **Worst ψ error across everything: ", fmt(worst_by_state[wi]),
        "** (state (n,l,m)=", all_states[wi], ")")
println(report, "- For context: one 16-bit output step = ", fmt(1 / 65535),
        "; one 8-bit step = ", fmt(1 / 255), ". The worst FP32-pipeline error ",
        "is ", @sprintf("%.2f", worst_by_state[wi] / (1 / 65535)),
        "× a 16-bit LSB and ", @sprintf("%.4f", worst_by_state[wi] / (1 / 255)),
        "× an 8-bit LSB.")

# -----------------------------------------------------------------------------
# 6. Display-stats grid convergence.
# -----------------------------------------------------------------------------
println(report, "\n## 6. Display-stats grid convergence\n")
worst_shift = 0.0
worst_id = (0, 0, 0, true)
for n in (4, 7, 10), l in (0, n - 1), mode in (true, false)
    m = l                                            # exercise the φ factor
    a = display_stats(n, l, m, mode)
    b = display_stats(n, l, m, mode; nr = 640, nu = 512, nφ = 128)
    shift = abs(a.q999 - b.q999) / b.q999
    if shift > worst_shift
        global worst_shift = shift
        global worst_id = (n, l, m, mode)
    end
end
println(report, "- Worst q999 shift when doubling the stats grid: **",
        fmt(worst_shift), "** at (n,l,m,real)=", worst_id,
        " — far below anything visible through a colormap.")

# -----------------------------------------------------------------------------
# Write the report.
# -----------------------------------------------------------------------------
out = joinpath(@__DIR__, "..", "validation_report.md")
write(out, String(take!(report)))
println("wrote ", abspath(out))
